version: '3'

services:
  db:
    image: postgres
    container_name: "is_db"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: is

  db-test:
    image: postgres
    container_name: "is_db-tests"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: is
