debug: true
spring:
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/is
    username: postgres
    password: password
  jackson:
    serialization:
      fail-on-empty-beans: false
